# Base image with Node.js
FROM node:18-alpine

# Set work directory
WORKDIR /app

# Install deps first
COPY package.json package-lock.json ./
RUN npm ci --omit=dev

# Copy rest of the code
COPY . .

# Build frontend (creates dist/)
RUN npm run build

# Expose Uptime Kuma default port
EXPOSE 3001

# Start app
CMD ["node", "server/server.js"]
