# ---- Base Image ----
FROM node:18-alpine AS build

# Set working dir
WORKDIR /app

# Install system deps
RUN apk add --no-cache \
  git \
  python3 \
  make \
  g++ \
  bash \
  tzdata \
  sqlite

# Copy files
COPY . .

# Install deps (ignore peer dependency conflicts)
RUN npm ci --omit=dev --legacy-peer-deps

# Build frontend
RUN npm run build

# ---- Runtime Image ----
FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache tzdata sqlite bash

COPY --from=build /app /app

# Default Kuma port
EXPOSE 3001

CMD ["node", "server/server.js"]
